version: 2
updates:
  # 1) npm (als Beispiel – dupliziere den Block je Ökosystem)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    reviewers:
      - "org/dependency-maintainers"   # optional Team/Benutzer
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Version-Updates bündeln (Minor & Patch -> 1 PR)
      npm-prod-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        dependency-type: production
      npm-dev-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        dependency-type: development

      # Security-Updates bündeln (kleine Sprünge)
      npm-security:
        applies-to: security-updates
        update-types: ["patch", "minor"]
    ignore:
      # Beispiel: laute Majors einzelner Pakete ausblenden
      - dependency-name: "webpack"
        update-types: ["major"]

  # 2) GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:10"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]
    groups:
      gha-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
