# .github/workflows/on-prerelease.yml
name: On Pre-Release
on:
  release:
    types: [prereleased]  # initial publish as prerelease + explicit prerelease action
jobs:
  on-prerelease:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo "Pre-release detected"
          echo "action=${{ github.event.action }}"
          echo "tag=${{ github.event.release.tag_name }}"
